# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aubrey Ryan Therapy
email: aubrey@aubreyryantherapy.com
description: "I'm Aubrey Ryan, a Chicago-based Marriage and Family Therapist. I specialize in personality disorders, family dynamics, marriage counseling and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aubreyryantherapy.com" # the base hostname & protocol for your site
tagline: Licensed Marriage and Family Therapist in Chicago
address: "561 W. Diversey #208, Chicago, IL, 60614"
phone: 872-222-8044
permalink: none

# Build settings
markdown: kramdown